Fix/err output (#10)
* init branch

* Implement nitpicks according to review comments

* Simplifying code and add console output of command being run for debugging purposes

* Remove erroneous quotes

* Remove erroneous newline

* Remove non-used vars

* Fix indentation

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -53,56 +53,124 @@ runs:
       id: bicep-deployment
       uses: azure/CLI@v2
       if: steps.resolve-deploymentconfig.outputs.deploy == 'true'
+      env:
+        SCOPE: ${{ steps.resolve-deploymentconfig.outputs.scope }}
+        PARAMETER_FILE: ${{ steps.resolve-deploymentconfig.outputs.parameter-file }}
+        DEPLOYMENT_NAME: ${{ steps.resolve-deploymentconfig.outputs.name }}
+        RESOURCE_GROUP: ${{ steps.resolve-deploymentconfig.outputs.resource-group }}
+        MANAGEMENT_GROUP_ID: ${{ steps.resolve-deploymentconfig.outputs.management-group-id }}
+        LOCATION: ${{ steps.resolve-deploymentconfig.outputs.location }}
+        WHAT_IF: ${{ inputs.what-if }}
+        DEBUG: ${{ runner.debug == '1' }}
       with:
         azcliversion: ${{ steps.resolve-deploymentconfig.outputs.azure-cli-version }}
         inlineScript: |
+          #* Enable strict mode
           set -euo pipefail
-          if [ "${{ steps.resolve-deploymentconfig.outputs.scope }}" = "resourceGroup" ]; then
-              deploymentOutput=$(az deployment group create \
-                --parameters '${{ steps.resolve-deploymentconfig.outputs.parameter-file }}' \
-                --name '${{ steps.resolve-deploymentconfig.outputs.name }}' \
-                --resource-group '${{ steps.resolve-deploymentconfig.outputs.resource-group }}' \
-                --verbose \
-                ${{ (inputs.what-if == 'true') && '--what-if' || '' }} \
-                ${{ (runner.debug == '1') && '--debug' || '' }} 2>stderr.txt | tee deployment.md)
-          elif [ "${{ steps.resolve-deploymentconfig.outputs.scope }}" = "subscription" ]; then
-              deploymentOutput=$(az deployment sub create \
-                --parameters '${{ steps.resolve-deploymentconfig.outputs.parameter-file }}' \
-                --name '${{ steps.resolve-deploymentconfig.outputs.name }}' \
-                --location '${{ steps.resolve-deploymentconfig.outputs.location }}' \
-                --verbose \
-                ${{ (inputs.what-if == 'true') && '--what-if' || '' }} \
-                ${{ (runner.debug == '1') && '--debug' || '' }} 2>stderr.txt | tee deployment.md)
-          elif [ "${{ steps.resolve-deploymentconfig.outputs.scope }}" = "managementGroup" ]; then
-              deploymentOutput=$(az deployment mg create \
-                --parameters '${{ steps.resolve-deploymentconfig.outputs.parameter-file }}' \
-                --name '${{ steps.resolve-deploymentconfig.outputs.name }}' \
-                --management-group-id '${{ steps.resolve-deploymentconfig.outputs.management-group-id }}' \
-                --location '${{ steps.resolve-deploymentconfig.outputs.location }}' \
-                --verbose \
-                ${{ (inputs.what-if == 'true') && '--what-if' || '' }} \
-                ${{ (runner.debug == '1') && '--debug' || '' }} 2>stderr.txt | tee deployment.md)
-          elif [ "${{ steps.resolve-deploymentconfig.outputs.scope }}" = "tenant" ]; then
-              deploymentOutput=$(az deployment tenant create \
-                --parameters '${{ steps.resolve-deploymentconfig.outputs.parameter-file }}' \
-                --name '${{ steps.resolve-deploymentconfig.outputs.name }}' \
-                --location '${{ steps.resolve-deploymentconfig.outputs.location }}' \
-                --verbose \
-                ${{ (inputs.what-if == 'true') && '--what-if' || '' }} \
-                ${{ (runner.debug == '1') && '--debug' || '' }} 2>stderr.txt | tee deployment.md)
-          fi
 
-          sed -i -e '1s/^/```diff\n/' -e '$a```' -e 's/~/!/g' -e 's/^[ \t]*//' deployment.md
+          #* Multiline annotation replacement function
+          format_multiline_annotation() {
+            #* Input: A multiline string
+            #* Output: The string formatted for GitHub annotations
 
-          if grep -q "ERROR:" stderr.txt; then
-              echo "::error::An error occurred during deployment. See error details in below"
-              cat stderr.txt
-              exit 1
-          fi
+            local input="$1"
 
+            #* Replace newlines with %0A to support multiline annotations in GitHub workflows
+            local formatted_string=$(echo "$input" | sed ':a;N;$!ba;s/\n/%0A/g')
+
+            #* Output the formatted string
+            echo "$formatted_string"
+          }
+
+          #* Cleanup function
+          touch stderr.log
+          print_stderr() {
+            #* Read the file line by line
+            while IFS= read -r line; do
+              if [[ $line == WARNING:* ]]; then
+                #* Extract the WARNING message and print it in yellow
+                echo -e "\e[33m${line#WARNING: }\e[0m"
+              elif [[ $line == INFO:* ]]; then
+                #* Print the INFO message in the default color
+                echo "${line#INFO: }"
+              elif [[ $line == ERROR:* ]]; then
+                #* Extract the JSON from the ERROR message
+                json=${line#ERROR: }
+                #* Pretty-print the JSON and apply red color to each line, suppressing extra lines
+                formatted_json=$(echo "$json" | jq . 2>/dev/null | while IFS= read -r json_line || [[ -n $json_line ]]; do
+                  echo -e "\e[31m${json_line}\e[0m"
+                done)
+                annotation_json=$(format_multiline_annotation "$formatted_json")
+                echo "::error::An error occurred during deployment. See error details in below%0A${annotation_json}"
+              fi
+            done <stderr.log
+          }
+
+          #* Set trap to call the cleanup function on ERR
+          trap print_stderr ERR
+
+          #* Create deployment command
+          cmd=()
+          case $SCOPE in
+          resourceGroup)
+            cmd+=("az deployment group create")
+            cmd+=("--resource-group $RESOURCE_GROUP")
+            ;;
+          subscription)
+            cmd+=("az deployment sub create")
+            cmd+=("--location $LOCATION")
+            ;;
+          managementGroup)
+            cmd+=("az deployment mg create")
+            cmd+=("--location $LOCATION")
+            cmd+=("--management-group-id $MANAGEMENT_GROUP_ID")
+            ;;
+          tenant)
+            cmd+=("az deployment tenant create")
+            cmd+=("--location $LOCATION")
+            ;;
+          *)
+            echo "::error::Unknown deployment scope." >&2
+            exit 1
+            ;;
+          esac
+
+          #* Add common parameters
+          cmd+=("--parameters $PARAMETER_FILE")
+          cmd+=("--name $DEPLOYMENT_NAME")
+          cmd+=("--verbose")
+          cmd+=($([[ $WHAT_IF == 'true' ]] && echo "--what-if" || echo ""))
+          cmd+=($([[ $DEBUG == 'true' ]] && echo "--debug" || echo ""))
+
+          #* Print command
+          echo "Running command:"
+          printf "%s\n" "$(
+            printf "%s \\\\\n" "${cmd[@]}" |              #* Print each array element followed by " \\"
+              awk 'NR==1 {print; next} {print "  " $0}' | #* Add two spaces before all lines except the first
+              sed '$ s/ \\$//'                            #* Remove the trailing slash from the last line
+          )"
+
+          #* Run deployment command
+          deploymentOutput=$($(echo "${cmd[@]}") 2> >(tee stderr.log >&2) | tee stdout.log)
+
+          #* Write the result to console
           echo "$deploymentOutput"
 
-          echo "deploymentOutput=$(echo $deploymentOutput)" >> "$GITHUB_OUTPUT"
+          #* Write success annotation
+          formatted_json=$(echo "$deploymentOutput" | jq . 2>/dev/null)
+          annotation_json=$(format_multiline_annotation "$formatted_json")
+          echo "::notice::Bicep template successfully deployed. Result:%0A${annotation_json}"
+
+          #* Format markdown code block and output to deployment.md
+          sed \
+            -e '1s/^/```diff\n/' \
+            -e '$a```' \
+            -e 's/~/!/g' \
+            -e 's/^[ \t]*//' \
+            stdout.log >deployment.md
+
+          #* Write as github output
+          echo "deploymentOutput=$(echo $deploymentOutput)" >>"$GITHUB_OUTPUT"
 
     - name: Add info to the deployment file
       id: deployment-info
@@ -127,8 +195,15 @@ runs:
       uses: mshick/add-pr-comment@v2
       with:
         message-id: ${{ steps.resolve-deploymentconfig.outputs.parameter-file }}
-        message-path: |
-          deployment.md
+        message-path: deployment.md
+
+    - name: Clean created files
+      shell: bash
+      run: |
+        rm -f deployment.md
+        rm -f commitMessageAndId.md
+        rm -f stdout.log
+        rm -f stderr.log
 
 outputs:
   deployment-output:
