Test output

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -53,6 +53,15 @@ runs:
       id: bicep-deployment
       uses: azure/CLI@v2
       if: steps.resolve-deploymentconfig.outputs.deploy == 'true'
+      env:
+        scope: ${{ steps.resolve-deploymentconfig.outputs.scope }}
+        parameter_file: ${{ steps.resolve-deploymentconfig.outputs.parameter-file }}
+        deployment_name: ${{ steps.resolve-deploymentconfig.outputs.name }}
+        resource_group: ${{ steps.resolve-deploymentconfig.outputs.resource-group }}
+        management_group_id: ${{ steps.resolve-deploymentconfig.outputs.management-group-id }}
+        location: ${{ steps.resolve-deploymentconfig.outputs.location }}
+        what_if: ${{ inputs.what-if }}
+        debug: ${{ runner.debug }}
       with:
         azcliversion: ${{ steps.resolve-deploymentconfig.outputs.azure-cli-version }}
         inlineScript: |
@@ -100,52 +109,58 @@ runs:
           trap print_stderr ERR
 
           deploymentOutput=$({
-            #* Resource Group scope
-            if [ "${{ steps.resolve-deploymentconfig.outputs.scope }}" = "resourceGroup" ]; then
+            case $scope in
+              "resourceGroup")
                 az deployment group create \
-                  --parameters '${{ steps.resolve-deploymentconfig.outputs.parameter-file }}' \
-                  --name '${{ steps.resolve-deploymentconfig.outputs.name }}' \
-                  --resource-group '${{ steps.resolve-deploymentconfig.outputs.resource-group }}' \
+                  --parameters "$parameter_file" \
+                  --name "$deployment_name" \
+                  --resource-group "$resource_group" \
                   --verbose \
-                  ${{ (inputs.what-if == 'true') && '--what-if' || '' }} \
-                  ${{ (runner.debug == '1') && '--debug' || '' }}
+                  $( [ $what_if = 'true' ] && echo "--what-if" ) \
+                  $( [ $debug = '1' ] && echo "--debug" )
+                ;;
 
-            #* Subscription scope
-            elif [ "${{ steps.resolve-deploymentconfig.outputs.scope }}" = "subscription" ]; then
+              "subscription")
                 az deployment sub create \
-                  --parameters '${{ steps.resolve-deploymentconfig.outputs.parameter-file }}' \
-                  --name '${{ steps.resolve-deploymentconfig.outputs.name }}' \
-                  --location '${{ steps.resolve-deploymentconfig.outputs.location }}' \
+                  --parameters "$parameter_file" \
+                  --name "$deployment_name" \
+                  --location "$location" \
                   --verbose \
-                  ${{ (inputs.what-if == 'true') && '--what-if' || '' }} \
-                  ${{ (runner.debug == '1') && '--debug' || '' }}
+                  $( [ $what_if = 'true' ] && echo "--what-if" ) \
+                  $( [ $debug = '1' ] && echo "--debug" )
+                ;;
 
-            #* Management Group scope
-            elif [ "${{ steps.resolve-deploymentconfig.outputs.scope }}" = "managementGroup" ]; then
-              az deployment mg create \
-                --parameters '${{ steps.resolve-deploymentconfig.outputs.parameter-file }}' \
-                --name '${{ steps.resolve-deploymentconfig.outputs.name }}' \
-                --management-group-id '${{ steps.resolve-deploymentconfig.outputs.management-group-id }}' \
-                --location '${{ steps.resolve-deploymentconfig.outputs.location }}' \
-                --verbose \
-                ${{ (inputs.what-if == 'true') && '--what-if' || '' }} \
-                ${{ (runner.debug == '1') && '--debug' || '' }}
+              "managementGroup")
+                az deployment mg create \
+                  --parameters "$parameter_file" \
+                  --name "$deployment_name" \
+                  --management-group-id "$management_group_id" \
+                  --location "$location" \
+                  --verbose \
+                  $( [ $what_if = 'true' ] && echo "--what-if" ) \
+                  $( [ $debug = '1' ] && echo "--debug" )
+                ;;
 
-            #* Tenant scope
-            elif [ "${{ steps.resolve-deploymentconfig.outputs.scope }}" = "tenant" ]; then
-              az deployment tenant create \
-                --parameters '${{ steps.resolve-deploymentconfig.outputs.parameter-file }}' \
-                --name '${{ steps.resolve-deploymentconfig.outputs.name }}' \
-                --location '${{ steps.resolve-deploymentconfig.outputs.location }}' \
-                --verbose \
-                ${{ (inputs.what-if == 'true') && '--what-if' || '' }} \
-                ${{ (runner.debug == '1') && '--debug' || '' }}
-            fi
+              "tenant")
+                az deployment tenant create \
+                  --parameters "$parameter_file" \
+                  --name "$deployment_name" \
+                  --location "$location" \
+                  --verbose \
+                  $( [ $what_if = 'true' ] && echo "--what-if" ) \
+                  $( [ $debug = '1' ] && echo "--debug" )
+                ;;
+
+              *)
+                echo "::error::Undefined deployment scope."
+                exit 1
+
+            esac
           } 2> >(tee stderr.log >&2) | tee stdout.log)
 
           #* Write the result to console
           echo "$deploymentOutput"
-          
+
           #* Write success annotation
           echo "::notice::Bicep template successfully deployed."
 
